module.exports.APP_CONFIG = {
    MONGO_CLUSTER_URI: process.env.MONGO_CLUSTER_URI,
    HTTP_PORT:process.env.HTTP_PORT,
    MONGO_LOCAL_URI:process.env.MONGO_LOCAL_URI,
    IMAGEKIT_PRIVATE_KEY: process.env.IMAGEKIT_PRIVATE_KEY,
    IMAGEKIT_PUBLIC_KEY: process.env.IMAGEKIT_PUBLIC_KEY,
    IMAGEKIT_ENDPOINT_URL: process.env.IMAGEKIT_ENDPOINT_URL,
    IMAGEKIT_INSTANCE_ID: process.env.IMAGEKIT_INSTANCE_ID,
  };